### ISSUE TITLE
ERROR:root:'CachingClient' object has no attribute 'options'

### ISSUE THREAD

**Issue by fahrradflucht** [rsteube/flik#6]
When trying to add a booking I get the following error:
`ERROR:root:'CachingClient' object has no attribute 'options'`

And I don't know if it is related but when I execute `flik list` I get:
`ERROR:root:module 'pendulum' has no attribute 'create'`

I don't think it is an authentication related issue because `projects`, `tasks` and `activities` is working fine.

**Comment by rsteube** [comment]
Might be a new dependency version (those aren't locked at the moment). Pendulum is a date related dependency, so it should be related. Are you using python3? We migrated from python2 some months ago. Will have a look in a couple of days when i'm back home.

**Comment by fahrradflucht** [comment]
my `/usr/local/bin/flik`'s shebang states `#!/usr/local/opt/python/bin/python3.7`, so I assume yes. But I'm not to familiar how this python language selection works. `python --version` states `2.7.10`...

**Comment by rsteube** [comment]
Should be fixed now, pendulum and zeep both had a small change in the newer version (renaming).
Either uninstall first or use `--upgrade` to get the new version, e.g.:

`pip install --user --upgrade git+https://github.com/rsteube/flik`

**Comment by fahrradflucht** [comment]
works, thanks 🎉
